Add Vienna music venues
mxstbr/awesome-austria pull request #23
Opened 2017-02-07 22:29 UTC by sotojuan

Hope you're doing great Max!

2017-02-08 09:06 UTC, mxstbr requested changes
Awesome! One tiny nitpick then we can ship this 🔥

2017-02-08 09:06 UTC, mxstbr commented on README.md
> +- [Music](#museums)
I doubt this is `#museums` 😉 let's also add Vienna as a subcategory here.

2017-02-08 14:05 UTC, sotojuan commented
Whoops. Should be fine now!

2017-02-12 16:49 UTC, mxstbr approved these changes

2017-02-12 16:50 UTC, mxstbr commented
Awesome thanks!

2017-02-12 16:50 UTC, merged